name: messeenger-client
version: 0.1.0
summary: Messeenger
description: Free chat app

confinement: strict
base: core18
grade: stable

slots:
  dbus-messeenger-client:
    interface: dbus
    bus: session
    name: thangved.thangved.messeenger_client

apps:
  super-cool-app:
    command: messeenger-client
    extensions: [ flutter-master ]
    plugs:
      - network
    slots:
      - dbus-messeenger-client
parts:
  super-cool-app:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
